<?
$PERM["news"]["G5"]="W";
$PERM["news"]["*"]="W";
$PERM["company"]["G5"]="W";
$PERM["company"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>